pytorch i used for deep learning and is used for making models for machine learning using unstructured data .
the main thing it uses is tensors they are builidng blocks.

In [2]:
import torch

torch.__version__

'2.3.1+cu121'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[2,17,3],[10,8,3]])

matrix

tensor([[ 2, 17,  3],
        [10,  8,  3]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
tensor = torch.tensor([[[1,2,3],[3,4,5],[8,9,0]]])

tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [8, 9, 0]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
rantensor = torch.rand(size=(3,4))
rantensor,rantensor.dtype

(tensor([[0.5115, 0.2549, 0.6983, 0.5914],
         [0.2713, 0.8234, 0.9620, 0.2233],
         [0.7222, 0.3853, 0.5157, 0.4695]]),
 torch.float32)

In [16]:
rantensor.shape

torch.Size([3, 4])

In [17]:
rantensor.ndim

2

In [18]:
rantensor.size

<function Tensor.size>

In [19]:
imgtensor = torch.rand(size=(224,224,3))
imgtensor.shape, imgtensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
imgtensor

tensor([[[0.4952, 0.3593, 0.3442],
         [0.4651, 0.9343, 0.3618],
         [0.5359, 0.8124, 0.2697],
         ...,
         [0.2051, 0.1520, 0.8093],
         [0.8607, 0.1355, 0.8411],
         [0.3510, 0.8205, 0.5737]],

        [[0.1530, 0.0563, 0.4230],
         [0.8482, 0.4437, 0.7354],
         [0.1433, 0.0372, 0.1344],
         ...,
         [0.5783, 0.2316, 0.8448],
         [0.3642, 0.8997, 0.8964],
         [0.4756, 0.4101, 0.6794]],

        [[0.4604, 0.3612, 0.7006],
         [0.4041, 0.4041, 0.0196],
         [0.9635, 0.0216, 0.4983],
         ...,
         [0.4229, 0.0101, 0.2683],
         [0.9403, 0.7611, 0.2059],
         [0.9769, 0.9314, 0.6946]],

        ...,

        [[0.3752, 0.3425, 0.6553],
         [0.7203, 0.1865, 0.6987],
         [0.0067, 0.9498, 0.1046],
         ...,
         [0.6338, 0.5203, 0.7801],
         [0.7585, 0.0148, 0.3751],
         [0.5904, 0.5146, 0.6382]],

        [[0.9551, 0.2206, 0.7866],
         [0.0065, 0.3071, 0.5338],
         [0.

In [21]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
one = torch.ones(size=(3,4))
one,one.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
dep  = torch.arange(start = 0,end = 10,step=1)
dep,dep.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [24]:
tenzo = torch.zeros_like(input=dep)
tenzo

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape ,float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
ftensor = torch.tensor([3.0,6.0,9.0],
                       dtype=torch.float16)

ftensor.dtype


torch.float16

In [32]:
tenso = torch.rand(3,4)

print(tenso)
print({tensor.shape})
print({tensor.dtype})
print({tensor.device})

tensor([[0.7762, 0.1704, 0.2977, 0.4337],
        [0.5016, 0.6075, 0.3189, 0.6002],
        [0.6033, 0.4952, 0.6361, 0.2590]])
{torch.Size([1, 3, 3])}
{torch.int64}
{device(type='cpu')}


In [33]:
tens = torch.tensor ([1,2,3])
tens * 10

tensor([10, 20, 30])

In [34]:
tens

tensor([1, 2, 3])

In [35]:
tens = tens - 10
tens

tensor([-9, -8, -7])

In [36]:
tens

tensor([-9, -8, -7])

In [38]:
tens = tens + 10
tens

tensor([11, 12, 13])

In [40]:
torch.multiply(tens,10)
tens

tensor([11, 12, 13])

In [42]:
tens

tensor([11, 12, 13])

In [43]:
tens*tens

tensor([121, 144, 169])

In [44]:
tens

tensor([11, 12, 13])

In [45]:
tens = tens - 10
tens

tensor([1, 2, 3])

In [46]:
tens

tensor([1, 2, 3])

In [48]:
import torch

tens = torch.tensor ([1,2,3])

tens.shape

torch.Size([3])

In [49]:
tens * tens

tensor([1, 4, 9])

In [50]:
tens.matmul(tens)

tensor(14)

In [51]:
tens @ tens

tensor(14)

In [55]:
%%time
value = 0
for i in range(len(tens)):
  value += tens[i] * tens[i]
value

CPU times: user 1.9 ms, sys: 33 µs, total: 1.93 ms
Wall time: 1.59 ms


tensor(14)

In [57]:
%%time
tens @ tens

CPU times: user 63 µs, sys: 974 µs, total: 1.04 ms
Wall time: 1.04 ms


tensor(14)

In [74]:
tensa=torch.tensor([[1,2,3],
                    [3,4,4],
                    [5,6,6]],dtype=torch.float32)

tensb=torch.tensor([[1,2],
                   [3,4],
                    [5,6]]
                   ,dtype=torch.float32)



In [63]:
print(tensa)
print(tensb)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [64]:
print(tensa)
print(tensb.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [65]:
output = torch.matmul(tensa,tensb.T)
print(output)
output.shape

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])


torch.Size([3, 3])

In [78]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3,out_features=6)

x=tensa
output=linear(x)

print(f'input shape : {x.shape}\n')
print (f'output:\n{output}\n\noutput shape: {output.shape}')

input shape : torch.Size([3, 3])

output:
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [2.4305, 1.6983, 2.2828, 1.1012, 2.4715, 2.2601],
        [4.0012, 2.7390, 3.4167, 1.4738, 4.0378, 3.1579]],
       grad_fn=<AddmmBackward0>)

output shape: torch.Size([3, 6])


In [81]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
print(x.max())
print(x.min())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [87]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [88]:
x.dtype

torch.int64

In [89]:
x16=x.type(torch.float16)
x16

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [94]:
x = torch.arange(1,8,1)
x
x.shape

torch.Size([7])

In [100]:
xr=x.reshape(1,7)
xr,xr.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [102]:
z=x.view(1,7)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [103]:
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [112]:
xs=torch.stack([x,x,x,x],dim=0)
xs

tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]])

In [114]:
xs=torch.stack([x,x,x,x],dim=1)
xs,xs.shape

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7]]),
 torch.Size([7, 4]))

In [116]:
xsque=xr.squeeze()
xsque,xsque.shape

(tensor([5, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [117]:
xsque=xr.unsqueeze(dim=0)
xsque,xsque.shape

(tensor([[[5, 2, 3, 4, 5, 6, 7]]]), torch.Size([1, 1, 7]))