pytorch i used for deep learning and is used for making models for machine learning using unstructured data .
the main thing it uses is tensors they are builidng blocks.

In [1]:
import torch

torch.__version__

'2.3.1+cu121'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [13]:
matrix = torch.tensor([[2,17,3],[10,8,3]])

matrix

tensor([[ 2, 17,  3],
        [10,  8,  3]])

In [10]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
tensor = torch.tensor([[[1,2,3],[3,4,5],[8,9,0]]])

tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [8, 9, 0]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
rantensor = torch.rand(size=(3,4))
rantensor,rantensor.dtype

(tensor([[0.4198, 0.5043, 0.8761, 0.1327],
         [0.6611, 0.6867, 0.9426, 0.9845],
         [0.9442, 0.9335, 0.2495, 0.9416]]),
 torch.float32)

In [22]:
rantensor.shape

torch.Size([3, 4])

In [23]:
rantensor.ndim

2

In [24]:
rantensor.size

<function Tensor.size>

In [25]:
imgtensor = torch.rand(size=(224,224,3))
imgtensor.shape, imgtensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
imgtensor

tensor([[[0.8736, 0.3393, 0.6445],
         [0.1920, 0.4792, 0.7149],
         [0.8356, 0.4282, 0.2331],
         ...,
         [0.4961, 0.6266, 0.5168],
         [0.3893, 0.4153, 0.1864],
         [0.3023, 0.2854, 0.0162]],

        [[0.6702, 0.3594, 0.6667],
         [0.8065, 0.0450, 0.8641],
         [0.5310, 0.1213, 0.9286],
         ...,
         [0.0604, 0.8808, 0.8353],
         [0.9104, 0.8852, 0.6615],
         [0.9280, 0.7313, 0.3725]],

        [[0.4269, 0.6399, 0.5239],
         [0.3142, 0.9505, 0.4625],
         [0.7903, 0.8863, 0.7637],
         ...,
         [0.2200, 0.0161, 0.9962],
         [0.8094, 0.6064, 0.1593],
         [0.6217, 0.8905, 0.1976]],

        ...,

        [[0.4846, 0.0556, 0.7586],
         [0.0470, 0.0903, 0.7959],
         [0.3900, 0.9599, 0.7254],
         ...,
         [0.5144, 0.8984, 0.6887],
         [0.1083, 0.7837, 0.5974],
         [0.8188, 0.8123, 0.2435]],

        [[0.6513, 0.1735, 0.0550],
         [0.1997, 0.5062, 0.0264],
         [0.

In [31]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [33]:
one = torch.ones(size=(3,4))
one,one.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [39]:
dep  = torch.arange(start = 0,end = 10,step=1)
dep,dep.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [40]:
tenzo = torch.zeros_like(input=dep)
tenzo

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])